### ISSUE TITLE
Sync ATX pool

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#1851] opened 2020-02-23 13:39 UTC
# Overview / Motivation
In order for us to support free standing atx, we must have referenced ATX either available in the mempool or in node DB. to allow this we must have the ability to sync ATX mempools with other nodes. also we might need the ability to persist ATXs in the mempool. 

# The Task
- [ ] Design the mempool sync process.
- [ ] implement mempool sync
- [ ] test

**Comment by almogdepaz** [comment] 2020-02-23 14:07
duplicate of #1063

**Closed as completed** 2021-05-13 10:45 UTC
