### ISSUE TITLE
Detailed node crash reason for Smapp

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#1736] opened 2020-01-27 13:46 UTC
When the node crashes, when possible, it should provide a reason to the Smapp.

The SMApp can use that reason to decide if the node should be re-started or not and so that it can display a meaningful reason to the user.

While most of this information could be derived from the logs, this would make a clunky mechanism.

One way to achieve this is to provide different exit codes which the Smapp could have a mapping for.

**Comment by moshababo** [comment] 2022-06-26 08:43
@lrettig @oriya still relevant?

**Comment by brusherru** [comment] 2022-06-26 11:25
Probably the issue is not relevant anymore. Check out this PRs in Smapp:
- https://github.com/spacemeshos/smapp/pull/764
- https://github.com/spacemeshos/smapp/pull/860 - this one requires details and we had decided with @dshulyak and @nkryuchkov that we will take details from node log

**Comment by brusherru** [comment] 2022-06-26 11:26
So, we can close it or if you know any other cases that we have to handle in the specific way - refine the issue, please.

**Closed as completed** 2022-06-27 21:24 UTC
