### ISSUE TITLE
Node panic

### ISSUE THREAD

**Issue by yaelmhoffman** [spacemeshos/go-spacemesh#1879] opened 2020-03-08 20:13 UTC
Application has a Node Start Error on app restart which requires the user to manually stop the go-spacemesh process.
<img width="1135" alt="Screenshot 2020-03-02 at 13 38 11" src="https://user-images.githubusercontent.com/56118594/76170356-df1f3680-6189-11ea-968d-bef82c91c8f0.png">

**Comment by avive** [comment] 2020-03-09 08:05
I was able to reproduce this in the following way:
1. Clean install - start syncing.
2. Setup smeshing/post.

You will get this node panic in some cases after you see in the log that the post file init is complete.
@moshababo @noamnelke @barakshani @IlyaVi 

It doesn't happen every time but quite frequently. There is no output of the panic in the log file. The last entry in the log file is the post init file write log entry.

**Comment by noamnelke** [comment] 2020-03-09 15:32
So no restart required (unlike the title of this issue)?

**Comment by avive** [comment] 2020-03-09 15:48
> So no restart required (unlike the title of this issue)?

correct. Also - the node starts just fine. It just panics when post init file setup is complete so I think the error dialog box is wrong in the app.

**Comment by avive** [comment] 2020-03-10 10:23
Looking at the stack trace - it looks like the exception is at activation.go:283 `close(b.initDone)`

**Comment by noamnelke** [comment] 2020-03-10 11:19
The most likely cause is a combination of #1714 and someone (the app?) calling `StartMining` more than once (or calling it once after passing `--start-mining`).

While #1714 will fix the `panic`, I think that calling `StartMining` more than once can have other unintended consequences.

**Comment by avive** [comment] 2020-03-10 11:40
It is likely that it is called more than once due to slow api response which makes the user thinks that nothing happens when he clicked next. We should probably disable 'next' once clicked until an api response is returned from the node. @IlyaVi

**Comment by noamnelke** [comment] 2020-03-10 12:08
We can (should?) also put protections on the side of the node. After #1714 is merged, it's worth making sure that further protection is even required.

**Comment by avive** [comment] 2020-03-10 17:50
@IlyaVi - we should definitely disable the 'next' button that triggers StartMining once clicked until the API returns a response. I've observed some cases where the user clicks next, nothing seems to happen so she just clicks next again - triggering another StartMining api request...

**Comment by avive** [comment] 2020-03-13 13:12
High confidence that 0.0.4 app and node v0.1.5 address this issue - I'm verifying this.

**Comment by avive** [comment] 2020-04-06 12:15
Fixed in 0.0.6

**Closed as completed by avive** 2020-04-06 12:15 UTC
