### ISSUE TITLE
Reuse allocations in hashing functions

### ISSUE THREAD

**Issue by poszu** [spacemeshos/go-spacemesh#5813] opened 2024-04-08 07:48 UTC
## Description

Related code:
https://github.com/spacemeshos/go-spacemesh/blob/591c4c06b681720e96987adfa6d94bd643521468/hash/hash.go#L16-L23

See https://github.com/spacemeshos/go-spacemesh/pull/5784/files/28480f57981d97fcc5a31a200cddd7136be4de66#r1553551388 for details.

**Comment by fasmat** [comment] 2024-04-15 13:58
Duplicate of https://github.com/spacemeshos/go-spacemesh/issues/5850

**Closed as completed by fasmat** 2024-04-15 13:58 UTC
