### ISSUE TITLE
flaky TestNIPostBuilderWithClients

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#5011] opened 2023-09-14 06:09 UTC
>      nipost_test.go:224: 
        	Error Trace:	/Users/runner/work/go-spacemesh/go-spacemesh/activation/nipost_test.go:224
        	            				/Users/runner/work/go-spacemesh/go-spacemesh/activation/nipost_test.go:158
        	Error:      	Received unexpected error:
        	            	poet service is unstable: getBestProof failed (builder: didn't receive any poet proof)
        	Test:       	TestNIPostBuilderWithClients

https://github.com/spacemeshos/go-spacemesh/actions/runs/6180990739/job/16778292302

@poszu @fasmat  i noticed that it started to fail recently, could be related to one of the changes

**Comment by poszu** [comment] 2023-09-15 07:59
I stumbled upon this in another PR too and hopefully fixed it within it (https://github.com/spacemeshos/go-spacemesh/pull/5003/commits/f0b39df66f239abc1e3c5560a5ed8039f57e7985). The fail is caused by the new _retry timeout_. Occasionally, the nipost builder tries to fetch the proof too soon and doesn't have time to retry.

**Comment by fasmat** [comment] 2023-09-15 11:04
With the fix from @poszu merged I think this issue can be closed now.

**Closed as completed by fasmat** 2023-09-15 11:04 UTC
