### ISSUE TITLE
go-spacemesh sync fails - stream reset

### ISSUE THREAD

**Issue by chrisxch** [spacemeshos/go-spacemesh#4693] opened 2023-07-12 10:01 UTC
## Description
Spacemesh can not sync due to being unable to read stream between peers.
Encoding issue?

## Steps to reproduce
Clone source
Fix checkpoint schema by removing 'command' as a required property
Build go-spacemesh
Download config
Run minimal setup:  ./go-spacemesh --config  ./config.testnet-05.json -d ./sm_data

## Actual Behavior
fetch failed to send batch
fetcher hash request failed
err: validation reject: malformed data: decode from buffer: not all bytes are consumed
err: stream reset

## Expected Behavior
Successful connection to peers

## Environment
Please complete the following information:
 - OS: RHEL distros, ie Rocky
 - Node Version: 
0.3.12-beta.0-1

**Comment by dshulyak** [comment] 2023-07-13 05:32
It doesn't look like distro problem. There were incompatible changes in types between versions, this error is "expected" in case of running new version with old data (or vice versa)

**Comment by chrisxch** [comment] 2023-07-13 07:59
I have edited this issue. Between dshulyak's comment and someone in discord reporting the same on Ubuntu I agree it isn't an OS issue.

**Comment by pigmej** [comment] 2023-07-13 08:22
@reythia the compatible version with testnet-05 is `v0.3.11-beta.3`

**Comment by dshulyak** [comment] 2023-07-13 08:25
compatible versions can be found at https://discover.spacemesh.io/networks.json
![image](https://github.com/spacemeshos/go-spacemesh/assets/1964576/a9c1cbd9-300d-45a4-8297-60078aecf048)

probably needs to be in some easier to access place, but i am closing as it is not a bug

**Closed as completed by dshulyak** 2023-07-13 08:25 UTC
Labels: bug
