### ISSUE TITLE
Hare: too many proposals

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#1007] opened 2019-06-19 12:38 UTC
# Overview / Motivation

only active identities in the proposal round should broadcast a proposal message. `ExpectedLeaders` configuration should determine the number of leaders in that round. 
though running the `AppTest` in `cmd/node` with `20` instances produces `20` proposal messages as the number of instances. even though `ExcpectedLeaders` is set to 5.

# The Task

Make sure the number of leaders sending proposal sets is correct. 

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by gavraz** [comment] 2019-07-11 07:23
Bug investigation
1. The problem occurred with both the fixed oracle and the regular oracle.
2. The problem is fixed for the fixed size oracle.
3. For the oracle - there are two configuration issues:
A - the active set size for genesis should be configurable (5/5 causes 1.0 probability for proposals).
B - the 'safe layer' parameter should be configurable (caused all layers to be considered genesis).

**Comment by gavraz** [comment] 2019-07-11 07:24
Closing the bug. Opened a task for 3A and 3B instead.

**Closed as completed by gavraz** 2019-07-11 07:24 UTC
Labels: bug
