### ISSUE TITLE
node crash: tx missing Header

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3291] opened 2022-06-22 16:18 UTC
## Description

this run had this crash.

https://github.com/spacemeshos/go-spacemesh/runs/7006924801?check_suite_focus=true

is the tx's header parsed correctly? @dshulyak 

```
2022-06-22 08:23:36 | panic: runtime error: invalid memory address or nil pointer dereference
-- | --
  |   | 2022-06-22 08:23:36 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe4f48c]
  |   | 2022-06-22 08:23:36 |  
  |   | 2022-06-22 08:23:36 | goroutine 920 [running]:
  |   | 2022-06-22 08:23:36 | github.com/spacemeshos/go-spacemesh/txs.orderTXs({0xc0015b3560?, {0xc0016fc370?, 0x0?}}, 0xc0013c04c0, 0x0?, {0xc0018169e0, 0x20, 0x20})
  |   | 2022-06-22 08:23:36 | /go/src/github.com/spacemeshos/go-spacemesh/txs/txs_builder.go:153 +0x16c
  |   | 2022-06-22 08:23:36 | github.com/spacemeshos/go-spacemesh/txs.getBlockTXs({0xc0015b3560?, {0xc0016fc370?, 0x761508b136f9f27e?}}, 0xff7770742a96862e?, 0xc0019de600?, {0xc0018169e0, 0x20, 0x20}, 0x0?)
  |   | 2022-06-22 08:23:36 | /go/src/github.com/spacemeshos/go-spacemesh/txs/txs_builder.go:192 +0x70
  |   | 2022-06-22 08:23:36 | github.com/spacemeshos/go-spacemesh/txs.(*ConservativeState).SelectBlockTXs(0xc000100140, {0x1259b18?}, {0xc002797560?, 0x24, 0x24})
  |   | 2022-06-22 08:23:36 | /go/src/github.com/spacemeshos/go-spacemesh/txs/conservative_state.go:112 +0x5a5
  |   | 2022-06-22 08:23:36 | github.com/spacemeshos/go-spacemesh/blocks.(*Generator).GenerateBlock(0xc0002c9b40, {0x1538c80?, 0xc001a6a300?}, {0x24f2900?}, {0xc002797560, 0x24, 0x24})
  |   | 2022-06-22 08:23:36 | /go/src/github.com/spacemeshos/go-spacemesh/blocks/generator.go:75 +0x203
  |   | 2022-06-22 08:23:36 | github.com/spacemeshos/go-spacemesh/hare.(*Hare).collectOutput(0xc0002dc8c0, {0x1538c80, 0xc001a6a300}, {0x1539888, 0xc0018eb6e0})
  |   | 2022-06-22 08:23:36 | /go/src/github.com/spacemeshos/go-spacemesh/hare/hare.go:255 +0x852
  |   | 2022-06-22 08:23:36 | github.com/spacemeshos/go-spacemesh/hare.(*Hare).outputCollectionLoop(0xc0002dc8c0, {0x1538c80, 0xc0003c83c0})
  |   | 2022-06-22 08:23:36 | /go/src/github.com/spacemeshos/go-spacemesh/hare/hare.go:461 +0x5d1
  |   | 2022-06-22 08:23:36 | created by github.com/spacemeshos/go-spacemesh/hare.(*Hare).Start
  |   | 2022-06-22 08:23:36 | /go/src/github.com/spacemeshos/go-spacemesh/hare/hare.go:530 +0x76a

```

**Comment by dshulyak** [comment] 2022-06-22 16:28
Usually it is parsed correctly :) but header will be nil, if tx is downloaded as a reference (e.g. sync), and the header is only parsed before applying such transaction

**Comment by dshulyak** [comment] 2022-06-22 16:35
i think that in my pr codepath for transactions that are downloaded as a part of the proposal is simply not handled. honestly i don't even know how to handle it correctly, there is no guarantee that previous block was applied when hare builds a new one. so transaction that may have been included into the block by consensus may not be verifiable by the node that synced it.

**Comment by dshulyak** [comment] 2022-06-22 16:37
it probably makes sense to revert my change. as i mentioned i can't think of any solution, except terminating hare if tx is not available locally

**Comment by countvonzero** [comment] 2022-06-22 16:50
is it possible to parse without verify for synced transactions?

UPDATE: i mean does it make sense? the design of tx *sometimes* have header doesn't seem natural to me.

**Comment by dshulyak** [comment] 2022-06-22 17:08
the problem is that parse_payload (method that parses nonce specifically and header) can be executed only after account was spawned. if it is spawned in the layer that is not yet applied - transaction can't be verified/parsed, or in other words it will simply fail. failing verification for transaction that is included in hare consensus or block verified by tortoise doesn't make sense. so the only solution is to delay parsing. atleast this is how i see it

**Comment by countvonzero** [comment] 2022-06-22 17:33
for this specific failure:
- there is still a chance for the tx to parse successfully. it skipped conservative cache only because it was synced, but we may already have the template deployed.
- for the account-not-spawned-yet txs, as you suggested earlier, it does seem the safe approach is to abort hare and utilize the certificate if available, or wait until tortoise verify a block for that layer.

for the overall design:
can you remind me why we need the dance of spawn then spend? i think it's part of the account abstraction but i forgot why.
can we require the very first tx (nonce==0) to provide a template?

**Comment by dshulyak** [comment] 2022-06-28 05:38
forgot to close it

**Closed as completed by dshulyak** 2022-06-28 05:38 UTC
Labels: bug
