### ISSUE TITLE
panic: failed to start smeshing: failed to prepare post initializer: fetch best provider: failed to fetch providers

### ISSUE THREAD

**Issue by bugxzhu** [spacemeshos/go-spacemesh#4713] opened 2023-07-16 11:59 UTC
## Description
run in docker-compose 

spacemesh    | panic: failed to start smeshing: failed to prepare post initializer: fetch best provider: failed to fetch providers
spacemesh    | 
spacemesh    | goroutine 1 [running]:
spacemesh    | go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x0?, {0x0?, 0x1?, 0x0?})
spacemesh    | 	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
spacemesh    | go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000794270, {0x0, 0x0, 0x0})
spacemesh    | 	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
spacemesh    | go.uber.org/zap.(*SugaredLogger).log(0xc000594fa8, 0x4, {0x19d05fb?, 0x0?}, {0xc0005951d0?, 0x2?, 0x2?}, {0x0, 0x0, 0x0})
spacemesh    | 	/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:295 +0xee
spacemesh    | go.uber.org/zap.(*SugaredLogger).Panicf(...)
spacemesh    | 	/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:189
spacemesh    | github.com/spacemeshos/go-spacemesh/log.Log.Panic({0xc0001b05b0?, {0x0?, 0xc000a2f340?}}, {0x19d05fb, 0x1c}, {0xc0005951d0, 0x1, 0x1})
spacemesh    | 	/src/log/zap.go:47 +0x1fa
spacemesh    | github.com/spacemeshos/go-spacemesh/log.Panic({0x19d05fb, 0x1c}, {0xc0005951d0, 0x1, 0x1})
spacemesh    | 	/src/log/log.go:171 +0x50
spacemesh    | github.com/spacemeshos/go-spacemesh/node.(*App).startServices(0xc0001a2160, {0x1d1e930?, 0xc0001309c0})
spacemesh    | 	/src/node/node.go:1008 +0x47d
spacemesh    | github.com/spacemeshos/go-spacemesh/node.(*App).Start(0xc0001a2160, {0x1d1e930, 0xc0001309c0})
spacemesh    | 	/src/node/node.go:1380 +0x1665
spacemesh    | github.com/spacemeshos/go-spacemesh/node.GetCommand.func1.1({0x1d1e930, 0xc0001309c0})
spacemesh    | 	/src/node/node.go:163 +0x368
spacemesh    | github.com/spacemeshos/go-spacemesh/node.GetCommand.func1(0xc00027a000?, {0x1842239?, 0xd?, 0xd?})
spacemesh    | 	/src/node/node.go:184 +0x387
spacemesh    | github.com/spf13/cobra.(*Command).execute(0xc00027a000, {0xc0001260f0, 0xd, 0xd})
spacemesh    | 	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
spacemesh    | github.com/spf13/cobra.(*Command).ExecuteC(0xc00027a000)
spacemesh    | 	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
spacemesh    | github.com/spf13/cobra.(*Command).Execute(...)
spacemesh    | 	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
spacemesh    | main.main()
spacemesh    | 	/src/cmd/node/main.go:24 +0xbb

docker-compose.yaml

version: '3'
services:
   spacemesh:
     container_name: spacemesh
     image: spacemesh:1.0.2
     runtime: nvidia
     environment:
       NVIDIA_VISIBLE_DEVICES: all
       NVIDIA_DRIVER_CAPABILITIES: compute,utility
     volumes:
       - ./entrypoint.sh:/root/entrypoint.sh
       - ./data:/data
       - ./data/spacemesh:/root/.spacemesh/
     entrypoint: ["/bin/bash","/root/entrypoint.sh"]
     logging:
       driver: "json-file"
       options:
         max-size: "5g"
     restart: always
     network_mode: "host"

entrypoint.sh
#!/bin/bash
echo "-----------star spacemesh------------------"
go-spacemesh --listen /ip4/0.0.0.0/tcp/7513 --config /data/config.mainnet.json -d data/smdata/ --smeshing-coinbase sm1qqqqqqrcr2pqeehzxxxxxxxxxxx --smeshing-start --smeshing-opts-datadir /data/post_data/ --smeshing-opts-numunits 4

**Comment by countvonzero** [comment] 2023-07-16 13:28
duplicate of #4708

**Closed as not planned by countvonzero** 2023-07-16 13:28 UTC
Labels: bug
