### ISSUE TITLE
hare: always terminates when round is advanced to certification round

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2942] opened 2021-11-16 03:26 UTC
## Description

In new devnet all hare instances are exiting with the following a warning, fortunately it doesn't break hare in general, just skips certification round.

```
103396:2021-11-16T04:52:21.000+0200	WARN	0b781.hare         	terminating: reached iterations limit	{"node_id": "0b781124139c036b35065aaec9999c19db3670453ae3ed4154052914ecf0d8c2", "module": "hare", "protocol": "HARE_PROTOCOL_tickloop", "sessionId": "9bcfd1ed-5df9-4d75-ad91-6ff0e9ec97d1", "limit": 10, "current_k": 2147483647, "layer_id": 236, "name": "hare"}
104060:2021-11-16T04:55:41.000+0200	WARN	0b781.hare         	terminating: reached iterations limit	{"node_id": "0b781124139c036b35065aaec9999c19db3670453ae3ed4154052914ecf0d8c2", "module": "hare", "protocol": "HARE_PROTOCOL_tickloop", "sessionId": "9bcfd1ed-5df9-4d75-ad91-6ff0e9ec97d1", "limit": 10, "current_k": 2147483647, "layer_id": 237, "name": "hare"}
104665:2021-11-16T04:59:01.000+0200	WARN	0b781.hare         	terminating: reached iterations limit	{"node_id": "0b781124139c036b35065aaec9999c19db3670453ae3ed4154052914ecf0d8c2", "module": "hare", "protocol": "HARE_PROTOCOL_tickloop", "sessionId": "9bcfd1ed-5df9-4d75-ad91-6ff0e9ec97d1", "limit": 10, "current_k": 2147483647, "layer_id": 238, "name": "hare"}
```

As you can see `"current_k": 2147483647`.

The termination condition is always true for certification round - https://github.com/spacemeshos/go-spacemesh/blob/develop/hare/algorithm.go#L388 as it is set to MaxUint32 >> 1.

## Steps to reproduce
run hare

## Actual Behavior
certification round is skipped

## Expected Behavior
certification round is not skipped

## Environment
Please complete the following information:
 - OS: 
 
 - Node Version: 
 
 - Smapp version (if applicable):

**Comment by jonZlotnik** [comment] 2022-05-20 16:14
Just adding some notes about the buggies so they'll be easy to fix.

Reason for terminating before certification round is run:

[If statement](https://github.com/spacemeshos/go-spacemesh/blob/7b062730d1db55ded328f588bca5ded21bed008f/hare/algorithm.go#L371) leads to hare termination because when we [advance to the "certification" round](
https://github.com/spacemeshos/go-spacemesh/blob/7b062730d1db55ded328f588bca5ded21bed008f/hare/algorithm.go#L366), we end up at [k= MaxUint32 >> 1](https://github.com/spacemeshos/go-spacemesh/blob/7b062730d1db55ded328f588bca5ded21bed008f/hare/algorithm.go#L560) as mentioned in the issue description, which is most definitely greater than the max iterations allowed for hare.

And the reason why we still make progress even though the certification round is skipped is that even though the protocol is terminated with a [call to `proc.Close()`](https://github.com/spacemeshos/go-spacemesh/blob/7b062730d1db55ded328f588bca5ded21bed008f/hare/algorithm.go#L375), we still [mark the protocol as completed](https://github.com/spacemeshos/go-spacemesh/blob/7b062730d1db55ded328f588bca5ded21bed008f/hare/algorithm.go#L820-L821) during the notify round and [send a terminationReport with the completed parameter set to true](https://github.com/spacemeshos/go-spacemesh/blob/7b062730d1db55ded328f588bca5ded21bed008f/hare/algorithm.go#L74).

**Comment by jonZlotnik** [comment] 2022-05-20 16:16
Questions to answer before pushing fix:

- [x] Are we allowed to still make progress (i.e. move to next layer) if the certification round is not completed?
- [ ] Do we want to add certification status to hare's termination report?

**Comment by dshulyak** [comment] 2022-05-20 16:28
>  Are we allowed to still make progress (i.e. move to next layer) if the certification round is not completed?

yes, hare is completely independent for every layer

> Do we want to add certification status to hare's termination report?

we want a certificate after hare reached consensus. if hare terminated without consensus (e.g. we will vote for empty layer) then we don't need a certificate

**Comment by countvonzero** [comment] 2022-05-20 17:46
> we want a certificate after hare reached consensus. if hare terminated without consensus (e.g. we will vote for empty layer) then we don't need a certificate

but i think using a certificate can avoid some tortoise vote delay tho.
for example, if a node's hare terminate without success (due to some unstable network connection) and before it gave up, it sees there is a certification, it can use it to advance the tortoise instead of voting for an empty layer.

**Comment by dshulyak** [comment] 2022-05-20 17:52
> but i think using a certificate can avoid some tortoise vote delay tho.
for example, if a node's hare terminate without success (due to some unstable network connection) and before it gave up, it sees there is a certification, it can use it to advance the tortoise instead of voting for an empty layer.

i dont follow. it makes sense to create a certificate when hare reached consensus, if it didn't reach the consensus - there is an option to certify empty block id. so that new nodes will vote for an empty layer immediately, without giving abstain votes within zdist.

UPD ah you are talking about condition when existing node didn't receive all notify messages, but instead received certification messages. i guess it is better and even more consistent with general hare approach to have a non optional last round

**Comment by countvonzero** [comment] 2022-05-20 18:04
> UPD ah you are talking about condition when existing node didn't receive all notify messages, but instead received certification messages. i guess it is better and even more consistent with general hare approach to have a non optional last round

yes. this is when i think even online smeshers can benefit from the certificate, not just in the sync case.

**Comment by jonZlotnik** [comment] 2022-08-18 21:10
implementation was replaced: https://github.com/spacemeshos/go-spacemesh/pull/3449

**Comment by countvonzero** [comment] 2022-08-18 21:32
duplicate of https://github.com/spacemeshos/go-spacemesh/issues/3199

**Closed as completed by countvonzero** 2022-08-18 21:32 UTC
Labels: bug
