### ISSUE TITLE
hare: produce a Certified Block upon hare termination

### ISSUE THREAD

**Issue by jonZlotnik** [spacemeshos/go-spacemesh#3283] opened 2022-06-22 03:32 UTC
AS A smeshing node who missed a hare consensus process and/or is syncing within hdist, I WANT a canonical certificate-like message that I can request from my peers on SO THAT I don't need to wait for Tortoise in order to vote and produce ballots on said layer.

### Implementation proposal overview
A new rolacle verifiable role in the hare protocol is defined as follows:
Upon receiving f+1 notify messages and generating the layer's block, if chosen by the rolacle, this party should sign the block and gossip both their eligibility proof for this role and the block signature. (block not included in message)

All other parties (active or not) should always be listening for the messages specified above. If one is received, it should be validated, verified, and stored for hdist layers. If ever requested for a Certified Block by a peer, they should provide the full Block along with as many of those signature messages as they've received for that layer up to f+1.

As a node requesting a Certified Block, I may need to contact multiple of my peers, and/or continue listening to gossip in order to accumulate enough block signatures to convince myself that it was truly the output of hare. This is especially the case in the couple layers leading up to the current layer.

### Potential for Failure
It is possible that the producing of a Certified Block for a given layer may fail (i.e. there is no guarantee that your peers will have collected f+1 signatures for you or that you will see them in gossip). In which case a smeshing node, who hadn't witnessed the hare protocol, may need to wait for Tortoise to catch up (worst case is waiting until the layer in question exits hdist).

**Comment by countvonzero** [comment] 2022-06-25 17:55
> this party should sign the block and gossip both their eligibility proof for this role and the block signature

it is enough to sign the BlockID (not the full block). after the node build the block, everything after that should operate on BlockID only. not the actual block content.

> AS A smeshing node who missed a hare consensus process and/or is syncing within hdist, I WANT a canonical certificate-like message that I can request from my peers on SO THAT I don't need to wait for Tortoise in order to vote and produce ballots on said layer.

for an online smesher, tortoise may catch up by counting ballots produced by other nodes.
for an syncing smesher, tortoise will be stuck.

**Comment by countvonzero** [comment] 2022-06-25 23:32
> for an syncing smesher, tortoise will be stuck.

i think i am wrong here, as the latest syncer code separates data sync and state sync. so tortoise just needs to wait past hdist to make progress.

**Comment by jonZlotnik** [comment] 2022-06-25 23:51
> 

Well a signature is assumed to be a hash + actual signature, so I'll try to make sure the blockID is what's actually being signed I guess.

**Comment by countvonzero** [comment] 2022-08-19 00:07
duplicate of #3199

**Closed as completed by countvonzero** 2022-08-19 00:07 UTC
