### ISSUE TITLE
MeshService.LayersQuery too slow and increase memo usage.

### ISSUE THREAD

**Issue by bobbychen** [spacemeshos/go-spacemesh#5393] opened 2023-12-25 04:07 UTC
## Description
MeshService.LayersQuery too slow and increase memo usage. while i'm using v1/mesh/layersquery integate smh.

## Steps to reproduce
curl --location --request POST 'http://localhost:9094/v1/mesh/layersquery' \ --header 'Content-Type: application/json' \ --data-raw '{     "start_layer":{"number":47176},     "end_layer":{"number":47176} }'

## Actual Behavior
always hang up.

## Expected Behavior
response result in reasonable time.

## Environment
Please complete the following information:
 - OS:  LINUX
 - Node Version: Latest.

**Comment by bobbychen** [comment] 2023-12-26 06:53
Update: hang on because the response contains activations info .btw How to filter activations in the server side?

**Comment by lrettig** [comment] 2023-12-26 21:13
This is a duplicate of #5315; it's being handled in #5334. Thanks for the report!

**Closed as not planned by lrettig** 2023-12-26 21:13 UTC
Labels: bug
