### ISSUE TITLE
Public key extraction in ed25519

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#669] opened 2019-03-17 10:58 UTC
# The Motivation
We enable public key extraction from signed messages. This results in shorter messages.

# The Requirement
Code revision is required:
- new signing algorithm
- extraction algorithm
- new functions: invert, modular multiplication, elliptic curve point multiplication

**Comment by avive** [comment] 2019-03-17 11:04
Please see this PR w the request for code review... https://github.com/spacemeshos/ed25519/pull/1

**Comment by lrettig** [comment] 2021-01-27 00:09
Duplicate of #670

**Closed as completed by lrettig** 2021-01-27 00:09 UTC
