### ISSUE TITLE
`Test_GenerateProof_TLS` failing

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#5344] opened 2023-12-12 21:18 UTC
## Description
`Test_GenerateProof_TLS` fails with the following error whenever I run it:

```
    post_service_test.go:176: 
        	Error Trace:	/home/runner/work/go-spacemesh/go-spacemesh/api/grpcserver/post_service_test.go:176
        	Error:      	Condition never satisfied
        	Test:       	Test_GenerateProof_TLS
        	Messages:   	timed out waiting for connection
    logger.go:130: 2023-12-12T21:04:15.419Z	INFO	grpc.TLS	stopping the grpc server
FAIL
```

See, e.g., https://github.com/spacemeshos/go-spacemesh/actions/runs/7187212252/job/19574309120?pr=5334

## Steps to reproduce
`UNIT_TESTS=github.com/spacemeshos/go-spacemesh/api/grpcserver make test`

## Actual Behavior
See above

## Expected Behavior
Test should pass

## Environment
Please complete the following information:
 - OS: Linux
 - Node Version: 730bda8ee21979e1a9c413d44b2801ac0d2f8f14

**Comment by fasmat** [comment] 2024-10-29 19:59
I cannot reproduce this error, since this ticket is already old and the issue is most likely fixed already I'm closing it. Feel free to re-open if the error reappears 🙂

**Closed as completed by fasmat** 2024-10-29 19:59 UTC
Labels: bug, area/testing
