### ISSUE TITLE
Install protoc in project directory to avoid permissions issue

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#1701] opened 2020-01-21 08:57 UTC
Our current `install-protobuf.sh` downloads `protoc` into `/usr/local/bin/` and `/usr/local/include/`. This changes the user's system for no good reason. We should install these files in the project directory and reference in these files when running them, later.

Problematic installation:
https://github.com/spacemeshos/go-spacemesh/blob/6b0785df47291fdcd994da8d11bbbfbc5eeab3b9/scripts/install-protobuf.sh#L22-L28

Usage:
https://github.com/spacemeshos/go-spacemesh/blob/6b0785df47291fdcd994da8d11bbbfbc5eeab3b9/scripts/genproto.sh#L8-L14

This will fix #1678 

TODO:
- [ ] Update `readme.md` to also use the local installation.

**Comment by moshababo** [comment] 2020-01-23 06:52
On Windows (`scripts/win/install-protobuf.bat`) it's installed under `%USERPROFILE%\protoc-3.6.1`.
Should it be changed as well?

**Comment by noamnelke** [comment] 2020-01-23 07:26
For the sake of consistency, I think yes.

**Comment by avive** [comment] 2020-01-26 06:38
This should be set to the open source readiness milestone and not for TN-1.0.

**Comment by lrettig** [comment] 2020-02-10 14:36
@avive okay - open source readiness is currently a "project" but there is no associated milestone yet. Let me know if you want to change this. I added this to the project.

**Comment by lrettig** [comment] 2020-08-12 17:31
Note that this will become obviated by #2078 - will leave this open until that's dealt with and all the protobuf tooling has been removed from go-spacemesh (hopefully soon).

**Comment by lrettig** [comment] 2020-10-15 01:18
duplicate of #2000, fixed in #2001. readme.md looks okay too.

**Closed as completed by lrettig** 2020-10-15 01:18 UTC
