### ISSUE TITLE
NTP sync failing in China

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2063] opened 2020-07-06 21:12 UTC
One of our users running a node in mainland China reports that he keeps losing his connection, and has to restart the app several times per day - although he is able to smesh and is receiving rewards. Here's a snipped from a recent logfile. Could anyone help me figure out what's going on here?

Some stuff I noticed:
- the node is unable to synchronize with several of the NTP servers, but it is able to reach the Apple Asia server
- it keeps bootstrapping, even though the address book is full
- there appear to be many P2P errors

Here's the log: https://gist.github.com/lrettig/968ce46ab928c29b87b5aceb5a9210b0

**Comment by y0sher** [comment] 2020-07-07 07:54
1. I'm still not sure about this error and why it shows up -
`read tcp 192.168.0.20:57275->35.184.140.134:20000: wsarecv: An existing connection was forcibly closed by the remote host.`
2. I see many bootstrap and that's ok. if we are missing good fresh neighbors we will keep querying our routing table for more. it doesn't mean we won't select and connect peers from our current list (we try maximum 10 bootstrap queries each time). so seeing a lot of bootstrap messages doesn't mean you aren't connected now.
I actually see that eventually TCP connections were formed but only with 3 peers and started syncing. (maybe some of the peers in the table are old and not working? I see 200+ which is not the number I recall from the testnet.) they will eventually be removed, a good note to our self is to check how much time it takes for them to be removed. because our managed miners don't query the network or change connections frequently then their address books stay quite unchanged. 
3. NTP - this looks like what actually causing the shutdowns.. maybe we should let users config their own ntp servers ?

**Comment by lrettig** [comment] 2020-07-08 22:25
> NTP - this looks like what actually causing the shutdowns.. maybe we should let users config their own ntp servers ?

I think this is the offending log line:

```
2020-06-29T23:38:45.480+0800	INFO	00000.defaultLogger	ntp check from server time.asia.apple.com, drift: -1.09178214s, start_check: 2020-06-29 15:38:45.3824234 +0000 UTC, latency: 0s, rsp: 2020-06-29 15:38:46.47420554 +0000 UTC
2020-06-29T23:38:45.480+0800	ERROR	30518.app          	System time couldn't synchronize NTP server errors [failed to read server response: read udp 192.168.0.20:64973->132.163.97.1:123: i/o timeout failed to read server response: read udp 192.168.0.20:62654->216.239.35.8:123: i/o timeout failed to read server response: read udp 192.168.0.20:62660->216.239.35.12:123: i/o timeout failed to read server response: read udp 192.168.0.20:62669->216.239.35.0:123: i/o timeout]	{"node_id": "30518"}
```

This is going to be an issue for probably everyone in China, and maybe other places besides. @noamnelke mentioned a few times that, instead of killing the node when the time drifts, the node should just track this internally. Maybe that's a better solution here?

Is there a short-term fix we can give this user? Maybe have him create hosts entries for the other NTP servers pointing to the Apple Asia server?

**Comment by noamnelke** [comment] 2020-07-13 16:22
Looks like you're right, it's Google's NTP server that's blocked (the offending IP address redirects to google.com).

While I stand behind my suggestion to compensate for drift instead of shutting down, and I think it won't be hard to implement, this is not the issue here... The problem isn't that there's drift, -1.09s is well within our 10s bound, it's that we can't verify the time with additional servers.

Compensating for known drift doesn't include being ok with not knowing what the drift is, which is what happened here.

Now, we can decide that a response from any single NTP server is enough for us. We could do this now and compensating for drift would also work the same way in the future if we do, but I'm not sure it's a great idea.

A better solution would probably be to stop using NTP at all and implement something like bitcoin does (syncing with peers, which we know we can reach).

**Comment by lrettig** [comment] 2020-07-13 19:16
@noamnelke would you be okay with a stopgap fix that allows a single NTP server for now, and that as a more permanent fix we implement the solution you proposed?

**Comment by lrettig** [comment] 2020-09-13 22:47
I'm looking at this again since it keeps getting reported - we have more smeshers in China and it keeps causing headaches for people there. Roughly in order from easy to hard/robust I see the following options to address this:

1. Lower the `MinResultsThreshold` for NTP server results from 3 to 1, for now:

https://github.com/spacemeshos/go-spacemesh/blob/ce9d5da1a17aee64458de361cbe4f85a03d1b49f/timesync/ntp.go#L27-L28

2. Include a larger pool of global NTP servers, including more that work in China

3. Allow the user to manually specify one or more NTP servers

4. Compensate for drift instead of shutting down (@noamnelke idea)

5. Stop using NTP at all and implement something like bitcoin does (syncing with peers, which we know we can reach) (@noamnelke idea)

@noamnelke and others, would appreciate your thoughts on this, if you have a preferred approach - if not, I suggest we go with the simplest for now and revisit later when we have more time to consider a more robust approach.

**Comment by noamnelke** [comment] 2020-09-14 07:17
I agree with the ordering, but... I think that doing 2 is almost as easy as 1 and has no tradeoff. I think skipping 1 and going straight to 2 is better. If we leave the threshold at 3, we need at least 4-5 servers that work in China.

Googling for a list of servers + adding them to the code = a couple of hours maybe
Creating a build of the testnet tag with the change cherry-picked on top + asking someone in China to test it = another hour

All in all, it's probably between half a day and a day to get 2 working, imo.

Here's where the list of servers is: https://github.com/spacemeshos/go-spacemesh/blob/ce9d5da1a17aee64458de361cbe4f85a03d1b49f/timesync/ntp.go#L33-L43

Extracting it to a config that the user can control doesn't seem like a big deal, either, but let's leave that to a later stage.

**Closed as completed** 2021-01-06 09:38 UTC
