### ISSUE TITLE
Error working with accounts from default genesis config

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#2024] opened 2020-05-14 11:51 UTC
## Description
Can't use accounts specified in default genesis config.

## Steps To Reproduce
1. Run a node on a network of v0.1.11 full nodes - make sure it is fully synced with a network.
2. Open a CLI wallet that connects to one of the net nodes, configured w the pub and private keys of the 2 tap accounts via its json data file.
3. Set tap1 or tap2 account as current.
4. INFO.

## Actual Behavior
$ info
<APP> INFO 00e 14:46:01.637 ▶ request: http://localhost:9090/v1/nonce, body: { "address": "0xc4eabd379d646beb6e065934cf7e9de59f8d43e7"}
<APP> INFO 00f 14:46:01.640 ▶ response body: {"error":"account does not exist","message":"account does not exist","code":2}
<APP> ERRO 010 14:46:01.640 ▶ failed to get account info: `/nonce` response status code: 500
> Local alias:  tap1
> Address:  0xc4eabd379d646beb6e065934cf7e9de59f8d43e7
> Balance:  
> Nonce:  
> Public key: 0xc007a95dc5b50c3ebbb8ff6bc4eabd379d646beb6e065934cf7e9de59f8d43e7

## Expected Behavior
API to return correct balance and nonce of the tap account and no error.

## Environment
OS X

**Comment by avive** [comment] 2020-05-17 13:10
Looks like this was a tn-c2s16-34 specific issue and not due to changes in genesis accounts code in v0.1.11. We should still try to understand how genesis accounts could not be used on it. @AmitShaul @ilans

**Comment by noamnelke** [comment] 2020-05-18 12:08
I don't think this issue can be caused by the network, it's a local issue. The node runs a genesis setup procedure when it sets up a new mesh, i.e. when the node starts up for the first time.

This procedure should update the tap accounts balance and nonce in the new global state.

I don't know why this didn't work this time, but I think that it would take considerable time to investigate and we're not sure it will ever happen again. Let's put this issue on hold and investigate only if we see this again. Closing for now.

**Closed as completed by noamnelke** 2020-05-18 12:08 UTC
Labels: bug
