### ISSUE TITLE
Flaky --- FAIL: TestRewardService_List/coinbase (0.00s)

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#5672] opened 2024-03-10 09:47 UTC
![image](https://github.com/spacemeshos/go-spacemesh/assets/1964576/45f0fa18-7802-4e6e-b93b-5e13cf9c50fb)

@kacpersaw

_Originally posted by @dshulyak in https://github.com/spacemeshos/go-spacemesh/issues/5669#issuecomment-1987163977_

**Comment by fasmat** [comment] 2024-03-11 14:58
Duplicate of https://github.com/spacemeshos/go-spacemesh/issues/5636

**Closed as completed by fasmat** 2024-03-11 14:58 UTC
Labels: area/api
